title: "Task Force Orange Blog"
description: "Updates, posts en meer"
repository: taskforceorange/blog
url: "https://taskforceorange.github.io"
baseurl: "/blog"

theme: minima
plugins:
  - jekyll-feed
